# Matrix

Matrix pada python merupakan sebuah 2 dimensional array yang menyimpan data pada `$Row$ dan $Column$`. Data didalam matrix dapat bertipe numbers, strings, expressions, symbols, etc.

In [3]:
#Membuat Matrix dengan metode Nested List
matrix = [[2,3], [4,6]]

print(matrix)

[[2, 3], [4, 6]]


> Pada code diatas memperlihatkan matrix tersebut memiliki 2 Rows dan 2 column
> Data didalam matrix tersebut merupakan $Number$
> Kolom pertama memiliki value `2,4` dan Kolom kedua memiliki value `3,6`

## Nested List

Dalam Python arrays direpresentasikan dengan menggunakan `list` data type <br><br>
Dan Nested list atau list didalam list, dapat digunakan untuk membuat matrix

In [36]:
#Matrix 2 x 2
mat1 = [[2, 3], [4, 6]]

#Matrix 4x5
mat2 = [[4.3, 2.3, 20.3,234], 
        [1.3, 7.5, 10.3,124],
        [9.0, 12.3, 4.8,0.2],
        [7.9, 3.7, 5.8,234],
        [8.7, 0.5, 3.4,788]]

#Callback Multiple list
first_row = [4, 8, 9]
second_row = [8, 0, 9]
mat3 = [first_row, second_row]

#Loop Matrix
mat4 = []
for i in range(5):
    mat4.append([])  
    for j in range(5):
        mat4[i].append(j)

print(f"mat1\n{mat1}\n\nmat2\n{mat2}\n\nmat3\n{mat3}\n\nmat4\n{mat4}")

mat1
[[2, 3], [4, 6]]

mat2
[[4.3, 2.3, 20.3, 234], [1.3, 7.5, 10.3, 124], [9.0, 12.3, 4.8, 0.2], [7.9, 3.7, 5.8, 234], [8.7, 0.5, 3.4, 788]]

mat3
[[4, 8, 9], [8, 0, 9]]

mat4
[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


Untuk Membaca matrix dalam bentuk Nested List kita dapat membacanya seperti kita memanggil list

In [35]:
#Membaca spesifik baris
print("Membaca spesifik Baris")
print(f"{mat3[0]}\n")

#Membaca spesifik value
print("Membaca spesifik value")
print(f"{mat3[0][1]}\n")

#Membaca spesifik kolom
print("Membaca spesifik Kolom")
print([row[1] for row in mat3])

Membaca spesifik Baris
[4, 8, 9]

Membaca spesifik value
8

Membaca spesifik Kolom
[8, 0]


### Matrix Comprehension

List Comprehension merupakan sebuah feature pada python yang sangat membantu dalam membuat sebuah list dengan iterasi sebuah object. Nested list comprehension tidak jauh beda dengan List comprehension, dimana sifat logikanya sama seperti nested untuk loops

Dalam Pembuatan Nested Loop Matrix dapat dilihat Code yang dipakai <br>
```
{
mat4 = []
for i in range(5):
    mat4.append([])  
    for j in range(5):
        mat4[i].append(j)
}
```

dan dengan memakai Nested List Comprehension dapat dibuat Seperti ini
```
{
mat4 = [[j for j in range(5)] for i in range(5)]
}
```
dan keduanya akan menghasilkan output yang sama, yaitu
```
[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
```

### Operasi pada Nested List Matrix

In [38]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

In [42]:
# Penjumlahan
penjumlahan = [[X[i][j] + Y[i][j]  for j in range(len(X[0]))] for i in range(len(X))]
print(f'Penjumlahan\n{penjumlahan}')

Penjumlahan
[[17, 15, 4], [10, 12, 9], [11, 13, 18]]


In [45]:
# Perkalian
perkalian = [[sum(X*Y for X,Y in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]
print(f'Perkalian\n{perkalian}')

Perkalian
[[114, 160, 60], [74, 97, 73], [119, 157, 112]]


In [44]:
# Transpose
transpose = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]
print(f'Before Transpose\n{X}')
print(f'After Transpose\n{transpose}')

Before Transpose
[[12, 7, 3], [4, 5, 6], [7, 8, 9]]
After Transpose
[[12, 4, 7], [7, 5, 8], [3, 6, 9]]


## Module Numpy

In [ ]:
#Install Module
!pip install numpy

In [46]:
import numpy as np

In [52]:
#Make the Matrix
mat1 = np.array([[2, 3], [4, 6]])

#Calling Existing Array
mat2, mat3, mat4 = np.array(mat2), np.array(mat3), np.array(mat4)

print(f"mat1\n{mat1}\n\nmat2\n{mat2}\n\nmat3\n{mat3}\n\nmat4\n{mat4}")


mat1
[[2 3]
 [4 6]]

mat2
[[4.30e+00 2.30e+00 2.03e+01 2.34e+02]
 [1.30e+00 7.50e+00 1.03e+01 1.24e+02]
 [9.00e+00 1.23e+01 4.80e+00 2.00e-01]
 [7.90e+00 3.70e+00 5.80e+00 2.34e+02]
 [8.70e+00 5.00e-01 3.40e+00 7.88e+02]]

mat3
[[4 8 9]
 [8 0 9]]

mat4
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### Read Matrix

In [57]:
#Membaca spesifik baris
print("Membaca spesifik Baris")
print(f"{mat3[0, :]}\n")

#Membaca spesifik value
print("Membaca spesifik value")
print(f"{mat3[0][1]}\n")

#Membaca spesifik kolom
print("Membaca spesifik Kolom")
print(mat3[:, 1])

Membaca spesifik Baris
[4 8 9]

Membaca spesifik value
8

Membaca spesifik Kolom
[8 0]


### Operation

In [58]:
X, Y = np.array(X), np.array(Y)

In [59]:
# Penjumlahan
penjumlahan = X + Y
print(penjumlahan)

[[17 15  4]
 [10 12  9]
 [11 13 18]]


In [60]:
# Perkalian
perkalian = X * Y
print(perkalian)

[[60 56  3]
 [24 35 18]
 [28 40 81]]


In [69]:
#Transpose
transpose = np.transpose(X)
print(f'Before Transpose\n{X}')
print(f'After Transpose\n{transpose}')

Before Transpose
[[12  7  3]
 [ 4  5  6]
 [ 7  8  9]]
After Transpose
[[12  4  7]
 [ 7  5  8]
 [ 3  6  9]]
