# Introduction to Python

## Data Types

### Boolean

Boolean adalah tipe data yang hanya mempunyai 2 nilai yaitu True atau False. Tipe data ini sering kali digunakan dalam comparison dan logical operators. Untuk comparison operator contohnya adalah sebagai berikut :
* a == b : a is equal to b
* a != b : a is different than b
* a < b : a is smaller than b
* a <= b: a is smaller or equal to b
* a > b: a is bigger than b
* a >= b: a is bigger or equal to b <br/>

Untuk logical operators dapat beberapa contohnya adalah sebagai berikut :<br/>
* a and b: True if both a and b are True. False otherwise.a == b: a is equal to b
* a or b: True if either a or b or both are True. False if both are False.
* not a: True if a is False, False if a is True.


In [3]:
print(1 < 10)

print("Linux" == "Windows")

print(1 != "1")

print(not True)

True
False
True
False


### String

String adalah tipe data yang memuat karakter/kalimat bisa berupa huruf, angka, dan sebagainya yang diapit tanda " atau '. Dalam python tipe data ini dinyatakan sebagai berikut :

In [4]:
color = "red"
print(type(color))

<class 'str'>


In [5]:
program_name = 'komstat 2'
program_year = "it's the 2nd"
multi_line = """hello,
email test.
signature."""
  
# let's
# "komstat 2"
print("let's\n\""+program_name+"\"")


print(len(''))  # 0
print(len(program_name)==8)  # False

let's
"komstat 2"
0
False


**Untuk mengakses substring, gunakan index atau slicing**.

Python mulai menghitung indeks dari 0 bukan 1. Indeks akses lebih besar dari panjangnya - 1, memicu indeks di luar jangkauan. Indeks negatif dimulai dari belakang.

Untuk mengakses substring, gunakan slicing, mirip dengan index, dengan range menggunakan tanda titik dua sebagai pemisah, dimulai dari angka pertama, sampai 1 kurang dari yang terakhir.

Sclicing dengan salah satu dari dua indeks berarti indeks lainnya adalah 0 untuk nilai pertama atau panjangnya untuk nilai kedua.

In [6]:
name = 'komstat 2'
print(name[1])  # o
print(name[len(name)-1])  # 2
print(name[-1])  # 2
print(name[-2])  # 2
  
print(name[4:len(name)-1])  # tat
  
print(name[:4])  # koms (0-3)
print(name[4:])  # tat 2  (4-len)

o
2
2
 
tat 
koms
tat 2


**String dalam Python tidak dapat diubah**

String dalam Python tidak dapat diubah, artinya tidak dapat dimodifikasi, tidak dapat mengubah karakter individu. Itu akan memicu objek TypeError tidak mendukung item assignment. Untuk mengubah string, ganti dengan string baru. Gunakan kata kunci in untuk memeriksa apakah substring merupakan bagian dari string.

In [7]:
year = "it's 2021"
year[-1] = "0"  # TypeError

TypeError: 'str' object does not support item assignment

### Integer

Tipe data integer adalah tipe data yang menyatakan bilangan bulat. Dalam python dapat dituliskan sebagai berikut :

In [8]:
length = 10
print(type(length))

<class 'int'>


### Float

Tipe data float adalah tipe data yang mempunyai desimal. Dalam python dapat dituliskan sebagai berikut :

In [9]:
width = 2.5
print(type(width))

<class 'float'>


### List

list adalah wadah dengan ruang di dalamnya dibagi menjadi slot yang berbeda. Setiap slot dapat berisi nilai yang berbeda. Python menggunakan tanda kurung siku [] untuk menunjukkan di mana indeks dimulai dan diakhiri. List indeks dimulai dari 0, seperti string, juga dapat melakukan slicing untuk mengembalikan list lain.

In [10]:
program_year = [2020, 2021]

print(type(program_year))    # list
print(program_year)
print(len(program_year))     # 2
print(2019 in program_year)  # False

print(program_year[0])       # 2020
print(program_year[:1])     # [2020]

for year in program_year:
    print(year)  # element per line


<class 'list'>
[2020, 2021]
2
False
2020
[2020]
2020
2021


Jika string tidak dapat diubah, list dapat diubah, artinya dapat menambah, menghapus, atau memodifikasi elemen dalam list.

Gunakan append untuk menambah elemen terakhir. Untuk menambahkan indeks tertentu, gunakan insert. Untuk menghapus elemen, gunakan hapus dengan elemen atau pop dengan indeks.

Untuk modifikasi elemen, ubah langsung ke indeks tertentu.

In [11]:
paths = ['Datmin', 'Komstat']
paths.append('Peramalan')
print(len(paths))  # 3
paths.remove('Peramalan')
paths.insert(1, 'Dasains')

# ['Datmin', 'Dasains', 'Komstat']
print(paths)
paths.append('Python')
paths.pop(-1)  # remove 'Python'

# change 'Datmin' to 'Data Mining'
paths[0] = 'Data Mining'
print(paths)


3
['Datmin', 'Dasains', 'Komstat']
['Data Mining', 'Dasains', 'Komstat']


### Tuple

Tuple seperti list. Mereka dapat berisi elemen dari tipe data apa pun. Tapi, tidak seperti list, tupel tidak dapat diubah. Python menggunakan tanda kurung () untuk menunjukkan di mana tuple dimulai dan diakhiri. Contoh tuple yang bagus adalah ketika suatu fungsi mengembalikan banyak nilai. String, list, dan Tuple disertakan sebagai tipe urutan. Dalam python dapat dituliskan sebagai berikut :

In [12]:
stat = (1, 3, 5, 7)
print(stat)  # (4, 16, 4.0)
print(type(stat))  # tuple

(1, 3, 5, 7)
<class 'tuple'>


### Dictionary

Seperti list, dictionary digunakan untuk mengatur elemen ke dalam koleksi. Tidak seperti list, dictionary tidak mengakses elemen di dalam menggunakan posisi (indeks). Data di dalam dictionary berbentuk pasangan key dan value. Untuk mendapatkan value dari dictionary, gunakan key yang sesuai. Tidak seperti indeks list harus berupa angka, tipe key dalam dictionary menggunakan string, bilangan bulat, tupel & lainnya. dictionary menggunakan kurung kurawal {}.

In [13]:
students = {
    'komstat 2': 60,
    'data mining': 90,
    'peramalan': 30
}
print(type(students))     # dict
print(students['peramalan'])  # 30

# keys: ['komstat', 'data mining', 'peramalan']
for key in students.keys():
    # eg: komstat 2:60
    print(key + ': '+ str(students[key]))

<class 'dict'>
30
komstat 2: 60
data mining: 90
peramalan: 30


# Function

Fungsi adalah blok kode yang hanya berjalan saat dipanggil. kita dapat meneruskan data, yang dikenal sebagai parameter, ke dalam suatu fungsi. Suatu fungsi dapat mengembalikan data sebagai hasilnya. Dalam Python fungsi memiliki beberapa aturan yaitu : 
* Tentukan fungsi dengan kata kunci def.
* Fungsi memiliki badan, ditulis sebagai blok setelah titik dua dalam definisi fungsi. Blok telah menjorok ke kanan.
* Untuk mendapatkan nilai dari suatu fungsi gunakan kata kunci return.


In [14]:
def greeting(name):
  return 'Hello, ' + name

print(greeting("Komstat 2 2023"))

Hello, Komstat 2 2023


# Control Flow

Barisan perintah dalam Python biasanya di eksekusi baris per baris. Dalam Python, barisan perintah dipisahkan dengan : diikuti dengan spasi dan indentasi sebagai satu group dipandang sebagai satu ekspresi tunggal dalam Python, tetapi barisan ekspresi yang dinyatakan dalam bentuk grup ini juga di execute baris perbaris. Untuk mengatur proses eksekusi, diperlukan perintah - perintah control flow. Bentuk control flow ini akan banyak digunakan dalam menulis suatu fungsi yang dibentuk oleh user. Beberapa perintah control flow yang dikenal di dalam Python sebagai berikut


# If Statement

In [15]:
def check(number):
    if number > 0:
        return "Positive"
    elif number == 0:
        return "Zero"
    else: 
        return "Negative"

print(check(10)) # Positive

Positive


## Match

Akan dievaluasi dari nilai expression, yang bernilai karakter atau numerik Nilai dari expression dibandingkan dengan nilai dari argumen setelahnya, jika cocok dengan salah satu, nilai dari argumen tersebut kemudian dimunculkan sebagai nilai dari fungsi switch. Fungsi ini dapat menggantikan nested if untuk melakukan multiple conditional.

In [16]:
lang = input("What's the programming language you want to learn? ")

match lang:
    case "JavaScript":
        print("You can become a web developer.")

    case "Python":
        print("You can become a Data Scientist")

    case "PHP":
        print("You can become a backend developer")
    
    case "Solidity":
        print("You can become a Blockchain developer")

    case "Java":
        print("You can become a mobile app developer")
    case _:
        print("The language doesn't matter, what matters is solving problems.")

The language doesn't matter, what matters is solving problems.


## For Loops

Syntax dasar fungsi sebagai berikut: <br/><br/>
for name in expression1: <br/>
&nbsp;&nbsp;&nbsp;&nbsp; expression2 <br/><br/>
Pertama akan dievaluasi nilai dari expression2 untuk setiap nilai di suatu barisan index di expression1. Dalam python dapat dituliskan sebagai berikut :


In [17]:
for x in range(3):
  print("x =" + str(x))

x =0
x =1
x =2


## While

Syntax dasar statement adalah sebagai berikut:
<br/><br/>
while <condition>:<br/>
&nbsp;&nbsp;&nbsp;&nbsp;# Jika kondisi benar<br/>
&nbsp;&nbsp;&nbsp;&nbsp;run_this_statement
<br/><br/>
Evaluasi nilai boolean dari condition, jika TRUE maka evaluasi nilai run_this_statement, kemudian kembali ke awal untuk mengevaluasi run_this_statement lagi. Dalam python dapat dituliskan sebagai berikut :


In [18]:
x = 7  # also try with x = 0

while x > 0:
  print("positive x=" + str(x))
  x = x - 1
  print("now x=" + str(x))

positive x=7
now x=6
positive x=6
now x=5
positive x=5
now x=4
positive x=4
now x=3
positive x=3
now x=2
positive x=2
now x=1
positive x=1
now x=0


# Data Frame

# Matrix

Matrix pada python merupakan sebuah 2 dimensional array yang menyimpan data pada $Row$ dan $Column$. Data didalam matrix dapat bertipe numbers, strings, expressions, symbols, etc.

In [19]:
#Membuat Matrix dengan metode Nested List
matrix = [[2,3], [4,6]]

print(matrix)

[[2, 3], [4, 6]]


> Pada code diatas memperlihatkan matrix tersebut memiliki 2 Rows dan 2 column
> Data didalam matrix tersebut merupakan $Number$
> Kolom pertama memiliki value `2,4` dan Kolom kedua memiliki value `3,6`

## Nested List

Dalam Python arrays direpresentasikan dengan menggunakan `list` data type <br><br>
Dan Nested list atau list didalam list, dapat digunakan untuk membuat matrix

In [20]:
#Matrix 2 x 2
mat1 = [[2, 3], [4, 6]]

#Matrix 4x5
mat2 = [[4.3, 2.3, 20.3,234], 
        [1.3, 7.5, 10.3,124],
        [9.0, 12.3, 4.8,0.2],
        [7.9, 3.7, 5.8,234],
        [8.7, 0.5, 3.4,788]]

#Callback Multiple list
first_row = [4, 8, 9]
second_row = [8, 0, 9]
mat3 = [first_row, second_row]

#Loop Matrix
mat4 = []
for i in range(5):
    mat4.append([])  
    for j in range(5):
        mat4[i].append(j)

print(f"mat1\n{mat1}\n\nmat2\n{mat2}\n\nmat3\n{mat3}\n\nmat4\n{mat4}")

mat1
[[2, 3], [4, 6]]

mat2
[[4.3, 2.3, 20.3, 234], [1.3, 7.5, 10.3, 124], [9.0, 12.3, 4.8, 0.2], [7.9, 3.7, 5.8, 234], [8.7, 0.5, 3.4, 788]]

mat3
[[4, 8, 9], [8, 0, 9]]

mat4
[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


Untuk Membaca matrix dalam bentuk Nested List kita dapat membacanya seperti kita memanggil list

In [21]:
#Membaca spesifik baris
print("Membaca spesifik Baris")
print(f"{mat3[0]}\n")

#Membaca spesifik value
print("Membaca spesifik value")
print(f"{mat3[0][1]}\n")

#Membaca spesifik kolom
print("Membaca spesifik Kolom")
print([row[1] for row in mat3])

Membaca spesifik Baris
[4, 8, 9]

Membaca spesifik value
8

Membaca spesifik Kolom
[8, 0]


### Matrix Comprehension

List Comprehension merupakan sebuah feature pada python yang sangat membantu dalam membuat sebuah list dengan iterasi sebuah object. Nested list comprehension tidak jauh beda dengan List comprehension, dimana sifat logikanya sama seperti nested untuk loops

Dalam Pembuatan Nested Loop Matrix dapat dilihat Code yang dipakai <br>
```
{
mat4 = []
for i in range(5):
    mat4.append([])  
    for j in range(5):
        mat4[i].append(j)
}
```

dan dengan memakai Nested List Comprehension dapat dibuat Seperti ini
```
{
mat4 = [[j for j in range(5)] for i in range(5)]
}
```
dan keduanya akan menghasilkan output yang sama, yaitu
```
[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
```

### Operasi pada Nested List Matrix

In [22]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

In [23]:
# Penjumlahan
penjumlahan = [[X[i][j] + Y[i][j]  for j in range(len(X[0]))] for i in range(len(X))]
print(f'Penjumlahan\n{penjumlahan}')

Penjumlahan
[[17, 15, 4], [10, 12, 9], [11, 13, 18]]


In [24]:
# Perkalian
perkalian = [[sum(X*Y for X,Y in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]
print(f'Perkalian\n{perkalian}')

Perkalian
[[114, 160, 60], [74, 97, 73], [119, 157, 112]]


In [25]:
# Transpose
transpose = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]
print(f'Before Transpose\n{X}')
print(f'After Transpose\n{transpose}')

Before Transpose
[[12, 7, 3], [4, 5, 6], [7, 8, 9]]
After Transpose
[[12, 4, 7], [7, 5, 8], [3, 6, 9]]


## Module Numpy

In [ ]:
#Install Module
!pip install numpy

In [26]:
import numpy as np

In [27]:
#Make the Matrix
mat1 = np.array([[2, 3], [4, 6]])

#Calling Existing Array
mat2, mat3, mat4 = np.array(mat2), np.array(mat3), np.array(mat4)

print(f"mat1\n{mat1}\n\nmat2\n{mat2}\n\nmat3\n{mat3}\n\nmat4\n{mat4}")


mat1
[[2 3]
 [4 6]]

mat2
[[4.30e+00 2.30e+00 2.03e+01 2.34e+02]
 [1.30e+00 7.50e+00 1.03e+01 1.24e+02]
 [9.00e+00 1.23e+01 4.80e+00 2.00e-01]
 [7.90e+00 3.70e+00 5.80e+00 2.34e+02]
 [8.70e+00 5.00e-01 3.40e+00 7.88e+02]]

mat3
[[4 8 9]
 [8 0 9]]

mat4
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### Read Matrix

In [28]:
#Membaca spesifik baris
print("Membaca spesifik Baris")
print(f"{mat3[0, :]}\n")

#Membaca spesifik value
print("Membaca spesifik value")
print(f"{mat3[0][1]}\n")

#Membaca spesifik kolom
print("Membaca spesifik Kolom")
print(mat3[:, 1])

Membaca spesifik Baris
[4 8 9]

Membaca spesifik value
8

Membaca spesifik Kolom
[8 0]


### Operation

In [29]:
X, Y = np.array(X), np.array(Y)

In [30]:
# Penjumlahan
penjumlahan = X + Y
print(penjumlahan)

[[17 15  4]
 [10 12  9]
 [11 13 18]]


In [31]:
# Perkalian
perkalian = X * Y
print(perkalian)

[[60 56  3]
 [24 35 18]
 [28 40 81]]


In [32]:
#Transpose
transpose = np.transpose(X)
print(f'Before Transpose\n{X}')
print(f'After Transpose\n{transpose}')

Before Transpose
[[12  7  3]
 [ 4  5  6]
 [ 7  8  9]]
After Transpose
[[12  4  7]
 [ 7  5  8]
 [ 3  6  9]]
